DROP TABLE IF EXISTS BLOG_POST;
DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USERR;

--USER TABLE
CREATE TABLE IF NOT EXISTS USERR (
    ID BIGSERIAL NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD  VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    PRIMARY KEY(ID)
);

--AUTHORITIES TABLE
CREATE TABLE IF NOT EXISTS AUTHORITIES(
	ID BIGSERIAL NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    AUTHORITY VARCHAR(255) NOT NULL
);

--BLOG TABLE
CREATE TABLE IF NOT EXISTS BLOG_POST (
	ID BIGSERIAL NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    DRAFT BOOLEAN NULL,
    PUBLISHDATE TIMESTAMP NULL,
    USER_ID BIGINT  NOT NULL,
    CONSTRAINT FK_BLOGPOST_USER FOREIGN KEY(USER_ID) REFERENCES USERR(ID)
);